BandWeb/Models/ViewModels/ArtistDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BandWeb.Models;

namespace BandWeb.Models.ViewModels
{
    public class ArtistDetailViewModel
    {
        public List<Artist> Artist { get; set; }

        public Artist artist { get; set; }
    }
}

BandWeb/Models/ViewModels/GetArtistViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BandWeb.Models.ViewModels
{
    public class GetArtistViewModel
    {
        public List<Artist> Artist { get; set; }
    }
}

BandWeb/Models/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BandWeb.Models.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [Display(Name = "Username")]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
    }
}

BandWeb/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BandWeb.Models;
using Newtonsoft.Json;
using BandWeb.Logic;
using BandWeb.Factory;
using BandWeb.Models.ViewModels;
using BandWeb.Logic.Interfaces;
using Microsoft.Extensions.Configuration;

namespace BandWeb.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountLogic _iaccountLogic;
        private readonly IConfiguration _iconfiguration;
        public AccountController(IConfiguration configuration)
        {
            _iconfiguration = configuration;
            _iaccountLogic = AccountFactory.CreateSqlLogic(_iconfiguration);
        }
        public IActionResult LoginForm()
        {
            return View();
        }
        public IActionResult LoginPage()
        {
            return View();
        }
        public IActionResult RegistrationSystem()
        {
            return View();
        }
        [HttpPost]
        public IActionResult LoginPage(LoginViewModel login)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Registrate(string username, string email, string password, string streetname, int housenumber, string city)
        {
            User user = new User(username, email, password, streetname, housenumber, city);

            try
            {
                _iaccountLogic.CreateUser(user);
                var accObject = user;
                HttpContext.Session.SetString("Account", JsonConvert.SerializeObject(accObject));
                return RedirectToAction("LoginPage", "Account");
            }
            catch (Exception e)
            {
                return Ok();
            }
        }
    }
}

BandWeb/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using BandWeb.Models;
using Newtonsoft.Json;
using BandWeb.Logic;
using BandWeb.Factory;
using BandWeb.Models.ViewModels;
using BandWeb.Logic.Interfaces;
using Microsoft.Extensions.Configuration;

namespace BandWeb.Controllers
{
    public class ArtistController : Controller
    {
        private readonly IArtistLogic _iartistLogic;
        private readonly IConfiguration _iconfiguration;
        public ArtistController(IConfiguration configuration)
        {
            _iconfiguration = configuration;
            _iartistLogic = ArtistFactory.CreateSqlLogic(_iconfiguration);
        }
        public IActionResult ArtistForm()
        {
            return View();
        }
        public IActionResult ArtistList()
        {
            var model = new GetArtistViewModel()
            {
                Artist = _iartistLogic.GetAllArtist().ToList(),
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult Detail(string id)
        {
            //var accObject = HttpContext.Session.GetString("Account");

            List<Artist> art = _iartistLogic.GetDetailArtist(id);
            ArtistDetailViewModel model = new ArtistDetailViewModel
            {
                Artist = art,
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Post(string nameArtist, string descriptionArtist,
           int listenersArtist, IFormFile image_pathArtist)
        {
            try
            {
                if (image_pathArtist != null)
                {
                    var path = Path.Combine
                    (
                        Directory.GetCurrentDirectory(),
                        "wwwroot",
                        "images",
                        image_pathArtist.FileName
                    );

                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await image_pathArtist.CopyToAsync(stream);
                    }
                }

                Artist art = new Artist(nameArtist, descriptionArtist, listenersArtist, image_pathArtist.FileName);

                _iartistLogic.NewArtist(art);
                return RedirectToAction("ArtistList");
            }
            catch (Exception ex)
            {
                return Content(ex.ToString());
            }
        }
    }
}

BandWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace BandWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BandWeb/Views/Artist/ArtistForm.cshtml
@using BandWeb.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ArtistForm";

}

<h2>Add a new Artist</h2>

<form asp-action="Post" enctype="multipart/form-data" method="post" class="form-horizontal">
    <fieldset>
        <legend></legend>
        <div class="form-group">
            <label class="control-label col-sm-3" for="nameArtist">Artist Name: </label>
            <div class="col-sm-10 input-breed">
                <input class="form-control" type="text" id="nameArtist" name="nameArtist" value="" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="descriptionArtist">Artist Description: </label>
            <div class="col-sm-10 input-breed">
                <input class="form-control" type="text" id="descriptionArtist" name="descriptionArtist" value="" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="listenersArtist">Amount of Listeners: </label>
            <div class="col-sm-10 input-smal">
                <input class="form-control" type="text" id="listenersArtist" name="listenersArtist" value="" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="image_pathArtist">Artist Picture: </label>
            <div class="col-sm-10 input-smal">
                <input type="file" id="image_pathArtist" name="image_pathArtist" />
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">&nbsp;</label>
            <div class="col-sm-10">
                <input type="submit" value="Add" class="btn btn-default" />
                <a asp-area="" asp-controller="Artist" asp-action="ArtistList" class="btn btn-default">Go back</a>
            </div>
        </div>
    </fieldset>
</form>

BandWeb/Views/Artist/ArtistList.cshtml
@using BandWeb.Models
@model BandWeb.Models.ViewModels.GetArtistViewModel
@{
    ViewData["Title"] = "ArtistList";
}

<br />
<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <a asp-controller="Artist" asp-action="ArtistForm">New Artist <span>+</span></a>
            <h1 class="my-4">Artists</h1>
            <div class="list-group">
                <b><a href="#" class="list-group-item">Pop</a></b>
                <b><a href="#" class="list-group-item">Rock</a></b>
                <b><a href="#" class="list-group-item">Jazz</a></b>
            </div>
        </div>
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">
            <div class="row">
                @foreach (Artist art in Model.Artist)
                {

                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <p style="text-align:">
                                <img class="card-img-top" style="border-radius: 50%;
                                     background-image: url(@art.image_path);
                                    height: 180px;
                                    width: 180px;
                                    background-position: center center;
                                    background-size: cover;" alt="">
                            </p>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a asp-controller="Artist" asp-action="Detail" asp-route-id="@art.id" class="">@art.name</a>
                                </h4>
                                <h5>@art.listeners Listeners</h5>
                                <p class="card-text">@art.description</p>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
@*<p>
        <a asp-controller="Artist" asp-action="ArtistForm">New Artist <span>+</span></a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Image</th>
                <th>Name</th>
                <th>Description</th>
                <th>Listeners</th>

                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Artist art in Model.Artist)
            {
                <tr>
                    <td>
                        @art.id
                    </td>
                    <td>
                        <img height="42" width="42" src="@art.image_path" />
                    </td>
                    <td>
                        @art.name
                    </td>
                    <td>
                        @art.description
                    </td>
                    <td>
                        @art.listeners
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                        @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                    </td>
                </tr>
            }
        </tbody>
    </table>*@

BandWeb/Views/Artist/Detail.cshtml
@using Microsoft.AspNetCore.Http
@using BandWeb.Models;
@model BandWeb.Models.ViewModels.ArtistDetailViewModel;
@{
    ViewData["Title"] = "Detail";
}
<h2>Detail</h2>
<div class="col-sm-5">
    <div class="adverContainer">
        <h2>Artist</h2>
        <div class="info">
            <p><b>id:</b> @Model.Artist[0].id</p>
            <p><b>Name:</b> @Model.Artist[0].name</p>
            <p><b>Description:</b> @Model.Artist[0].description</p>
            <p><b>Listeners:</b> @Model.Artist[0].listeners</p>
        </div>
    </div>
</div>

BandWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@using BandWeb.Models
@{
    ViewData["Title"] = "Home";
}

<h1> BandWeb</h1>

@*<script src="js/bootstrap/js/bootstrap.bundle.min.js"></script>*@

BandWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@using BandWeb.Models
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html class="contentwrapper">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proftaak.NET</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
        asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"></a>
            </div>
            <div class="navbar-collapse collapse navbar-left">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Artist" asp-action="ArtistList">ArtistList</a></li>
                    @*@if (!HttpContextAccessor.HttpContext.Session.Keys.Contains("Account"))
                {
                 <li><a asp-area="" asp-controller="Account" asp-action="LoginForm">LOGIN</a></li>
                }
                else
                {
                var accObject = HttpContextAccessor.HttpContext.Session.GetString("Account");
                Account acc = JsonConvert.DeserializeObject<Account>(accObject);
                <li><a asp-area="" asp-controller="Account" asp-action="Dashboard">DASHBOARD</a></li>
                <li><a asp-area="" asp-controller="Game" asp-action="Game">GAME</a></li>
                <li><a asp-area="" asp-controller="Shop" asp-action="Winkelpagina">WINKEL</a></li>
                }*@
                </ul>
            </div>
            <div class="navbar-collapse collapse navbar-right">
                <ul class="list-group">
                    <li><a class="list-group-item" asp-area="" asp-controller="Account" asp-action="LoginPage">Sign up</a></li>
                </ul>
            </div>
        </div>  
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @*<footer>
        <div class="footertekst">
        </div>
        <div class="sociaal">
        </div>

        <div class="partnerschap">
        </div>
    </footer>*@
    @RenderSection("Scripts", required: false)
</body>
</html>